### ISSUE TITLE
project：scheme有些小问的代码没有找到，是没写吗

### ISSUE THREAD

**Issue by wildboyy** [shuo-liu16/CS61A#2]
如题

**Comment by shuo-liu16** [comment]
很抱歉没有及时回复你的问题。实际上，我还没有完成这个项目。因为我对项目的整体概念理解不够深入，这让我在写作过程中感到有些困难。

也许是因为我有些拖延，但我会尽快完成这个项目。如果有需要，我们可以进一步交流。

**Comment by shuo-liu16** [comment]
我现在已经进行到第4部分了。如果在此之前的部分你有任何问题（仅scheme，之前的我已经忘得差不多了），或许我可以帮忙解答。当然，我也希望你的问题有一定的价值，而不是无关紧要的内容（可以发布在讨论部分）。
